### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-7htp9#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by prasoonmhwr** [comment]
<img width="1440" alt="Screenshot 2022-09-04 at 4 24 21 PM" src="https://user-images.githubusercontent.com/52622674/188310876-d414073d-c578-4cfb-af5f-65a3e0572338.png">
<img width="1440" alt="Screenshot 2022-09-04 at 4 24 29 PM" src="https://user-images.githubusercontent.com/52622674/188310878-7f815175-9ebf-4315-aa6a-3d6010bd518a.png">


Fixed
